name: {{project_name}}
description: {{description}}
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

dependencies:
  animations: ^2.0.11
  auto_route: ^8.0.0
  dartx: ^1.2.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  get_it: ^7.6.7
  icons_launcher: ^2.1.7
  injectable: ^2.3.2
  intl: ^0.18.1
  loader_overlay: ^4.0.0
  logger: ^2.2.0
  material_symbols_icons: ^4.2719.3
  package_info_plus: ^6.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: any
  custom_lint: any
  dependency_validator: ^3.2.3
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  riverpod_generator: ^2.4.0
  riverpod_lint: any
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  generate: true
